### ISSUE TITLE
Testing helper

### ISSUE THREAD

**Issue by iwakura** [vigetlabs/simplest_auth#1]
Hi,

Can you, please tell how to emulate user log in for functional testing?

Thanks

**Comment by iwakura** [comment]
Ok, solved for me.

```
class ActiveSupport::TestCase
  def log_in
    session[:user_id] = User.make.id
  end
end
```

Thanks

**Comment by reagent** [comment]
If you're using Mocha (included in newer versions of Rails), you can stub out the `current_user` method rather than directly setting session vars:

```
class ActionController::TestCase

  def login(user = nil)
    user = User.make if user.nil?
    @controller.stubs(:current_user).with().returns(user)
  end

end
```

To use it in your tests you can do this:

```
# log in as any user
login

# log in as a specific user
user = User.make(:first_name => 'Example')
login user
```

**Comment by iwakura** [comment]
Hello,
Thanks for suggestion, but it does not works for me.
I'm using flexmock instead mocha.
I call login method in setup block and
@controller instance variable is not initialized at that point.

**Comment by reagent** [comment]
Ah - the syntax for stubbing that controller method will be different, but the general approach should still work.  It sounds like you've got it working with the code you originally posted anyway.
