### ISSUE TITLE
bcrypt version is old

### ISSUE THREAD

**Issue by rubydesign** [vigetlabs/simplest_auth#7]
Hi, first of all very nice ! 
Seems to hit just hit the spot, as i am moving from AR -> datamapper and devise seems incompatible with paperclip.

I just had to fork to up the brypt version. dm-types need greater than 3 . 
I'm also on the rails-4 branch (could be documented?) but i hope that is appropriate for a new (rails4) app

thnks (can sens a pull if you want)

**Comment by tpitale** [comment]
The bcrypt requirement should be version >= 2.1.1. If you're seeing it as ~> 2.1.1 it may be due to an old rubygems version.

https://github.com/vigetlabs/simplest_auth/blob/master/simplest_auth.gemspec#L23
